### ISSUE TITLE
springboot整合dataway, 指定context-path: 之后请求xx/interface-ui/失败

### ISSUE THREAD

**Issue by lgw8186** [zycgit/hasor#12]
port: 8081
  connection-timeout: 5000ms
  servlet:
    context-path: /apic/v1/

有context-path: /apic/v1/ 配置，正常启动，请求失败。
去掉context-path后，正常启动，正常访问

<hasor.version>4.1.3</hasor.version>
<dataway.version>4.1.3-fix20200414</dataway.version>

**Comment by zycgit** [comment]
根据这几个参数的设置你改一下你的配置

`# 是否启用 Dataway 功能
HASOR_DATAQL_DATAWAY=true
# dataway  API工作路径
HASOR_DATAQL_DATAWAY_API_URL=/dataql/api/
# 是否开启 Dataway 后台管理界面（注意生产环境建议设置为 false）
HASOR_DATAQL_DATAWAY_ADMIN=true
# dataway-ui 的工作路径
HASOR_DATAQL_DATAWAY_UI_URL=/api-ui/
#SQL执行器在分页模式下的方言
HASOR_DATAQL_FX_PAGE_DIALECT=mysql`

**Comment by zycgit** [comment]
4.1.4 上已经修复。
