### ISSUE TITLE
能否支持多数据源切换？ 使用局部 hint

### ISSUE THREAD

**Issue by lgw8186** [zycgit/hasor#13]

**Comment by zycgit** [comment]
4.1.3 不支持多数据源，下一个版本预计可能会加入多数据源能力。 但也可能是 4.1.5。

**Comment by zycgit** [comment]
我在考虑通过局部  hint 方式来切换多数据源。 目前  hint 还只支持写在最前面，这部分改造还挺深的。

这需要在指令层面进行支持，首先 语法解析要支持局部 hint、AST 层面要增加一些属性来支持这个数据。最后 在指令层面在进行处理。

最后DataQL 写出来的样子应该类似这样：


```
var sql1 = @@sql()<%. …….. %>
var sql2 = @@sql()<%. …….. %>
{
    hint sql_source = "hsql"
    var data1 = sql1();
}

{
    hint sql_source = "hsql"
    var data1 = sql2();
}
```

**Comment by zycgit** [comment]
目前，语法层面、AST 层面已经能够支持。 指令层面还在思考如何实现局部 hint 。

**Comment by zycgit** [comment]
SQL执行器在 4.1.4 版本之后提供了可以通过 hint 来切换数据源的能力。在没有指定数据源 hint 的情况下数据源采用的是默认数据源，配置多个数据源的方式如下：

```
public class MyModule implements Module {
    public void loadModule(ApiBinder apiBinder) throws Throwable {
        DataSource defaultDs = ...;
        DataSource dsA = ...;
        DataSource dsB = ...;
        apiBinder.installModule(new JdbcModule(Level.Full, defaultDs));   // 默认数据源
        apiBinder.installModule(new JdbcModule(Level.Full, "ds_A", dsA)); // 数据源A
        apiBinder.installModule(new JdbcModule(Level.Full, "ds_B", dsB)); // 数据源B
    }
}
```

在DataQL中选择数据源：

```
// 如果不设置 FRAGMENT_SQL_DATA_SOURCE 使用的是 defaultDs 数据源。
//   - 设置值为 "ds_A" ，使用的是 dsA 数据源
//   - 设置值为 "ds_B" ，使用的是 dsB 数据源。
 hint FRAGMENT_SQL_DATA_SOURCE = "ds_A"
// 声明一个 SQL 
var dataSet = @@sql() <% select * from category limit 10; %> 
// 使用 特定数据源来执行SQL。
 return dataSet();
```

这是手册位置：https://www.hasor.net/web/dataql/fragment/sql/execute.html#id8

**Comment by zycgit** [comment]
4.1.4 已发布，提供了多数据源切换的能能力。

局部 hint 方式会继续支持。

**Comment by meglory** [comment]
> 4.1.4 已发布，提供了多数据源切换的能能力。
嗨，我这边本地跑4.1.4版本，发现在DataQL里，hint全都不生效，请问是什么原因呢？

**Comment by dzqw874396** [comment]
能否提供动态配置多数据源

**Comment by renzhaokun67** [comment]
> 4.1.4 已发布，提供了多数据源切换的能能力。
> 
> 局部 hint 方式会继续支持。

大大求局部数据源切换支持，我们现在表分在不同的库里面

**Comment by zycgit** [comment]
呃我尽量尽快支持， 局部 hint 需要对底层指令集做改进。会比较麻烦一些。

**Comment by sunpauliz** [comment]
做数据可视化时，针对多数据源的管理是动态的新增、修改的，但dataql中只能在启动时初始化，@zycgit 是否可以在运行期增删改datasource，同时，HASOR_DATAQL_FX_PAGE_DIALECT也需要适应多类型的数据源，目前只能统一设置为一种

**Comment by zycgit** [comment]
4.2.2 版本中提供 局部 hint 能力。通过 局部 hint 可以动态切换数据源。

![image](https://user-images.githubusercontent.com/4951471/97078413-c67f6600-161e-11eb-85ea-d1c4e2d53eda.png)

**Comment by zycgit** [comment]
@sunpauliz  目前可以通过 这两个接口来实现，不过数据源的管理目前还需要开发人员自己来管理。
LookupConnectionListener
LookupDataSourceListener

**Comment by zycgit** [comment]
@sunpauliz 你的问题我单独开一个 issue 来跟踪。这个 issue 主要是跟踪局部 hint 的，目前能力已经提供就关闭了。
