### ISSUE TITLE
springboot 1.5.10.RELEASE 集成 dataway

### ISSUE THREAD

**Issue by loannea** [zycgit/hasor#16]
看资料是springboot 的最低版本是 2.2.4.RELEASE
在1.5.10.RELEASE的环境下，只要开启 @EnableHasorWeb() 就 会报以下错误
propertySourcesPlaceholderConfigurer 注入失败 
`java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration.propertySourcesPlaceholderConfigurer
Caused by: java.lang.reflect.MalformedParameterizedTypeException: null`

![image](https://user-images.githubusercontent.com/34953193/80347317-bc162680-889e-11ea-8ff8-0e269c1f3fba.png)

**Comment by zycgit** [comment]
目前已知的是 2.x 上没问题。  1.x 的我试一下，看看能否兼容。

**Comment by zycgit** [comment]
same as https://github.com/zycgit/hasor/issues/58
