### ISSUE TITLE
文档中的例子错误

### ISSUE THREAD

**Issue by scofier** [zycgit/hasor#18]
下面文档中的例子执行报错
```sql
var dataSet = @@sql(item_code) <%
    select * from category where co_code = :item_code
%>
return dataSet() => [
    { "id","name","code","body" }
]
```

  "value": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':item_code' at line 1"

**Comment by zycgit** [comment]
感谢。 在下一次更新文档中会立刻修复。

**Comment by zycgit** [comment]
文档已经更正。
