### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by uuxii** [zycgit/hasor#19]
问下目前dataway有无一套内存缓存策略，如果每次访问mapping都增加了一次sql查询，感觉会产生额外开销，有无什么方法或者框架封装了一些像是ehcache、redis来实现mapping表的缓存呢？

**Comment by zycgit** [comment]
4.1.4 已经增加了缓存的 SPI 接口：https://www.hasor.net/web/dataway/spi.html

**Comment by zycgit** [comment]
4.1.4  已经发布。

**Comment by uuxii** [comment]
谢谢，已经更新包看效果了^_^
