### ISSUE TITLE
其他数据源的支持

### ISSUE THREAD

**Issue by xxmfypp** [zycgit/hasor#22]
DataWay是否可以增加ElasticSearch、Redis、Hive、HBASE等数据库的支持?

**Comment by zycgit** [comment]
这是一个非常好的建议。

**Comment by erchuinet** [comment]
> DataWay是否可以增加ElasticSearch、Redis、Hive、HBASE等数据库的支持?

看wiki是支持phoenix的，这样就支持Hbase了。其实我也有同样的想法：-）,一旦支持NoSQL数据库，ES，Redis，Hive，那使用场景就很丰富了。

**Comment by zycgit** [comment]
支持是一定要做的，这个最好是大家一起努力。

短期这里有一个活动，递交 PR 赢奖品。要支持的数据源就是  ES。

   - 指定的 Issue ：https://gitee.com/zycgit/hasor/issues/I1FHM5
   - 活动地址：https://gitee.com/Selected-Activities/gitee-7th-event-2/blob/master/issue-medium.md
