### ISSUE TITLE
SQL根据参数动态组装SQL

### ISSUE THREAD

**Issue by isking2008** [zycgit/hasor#23]
目前新增SQL，无法像mybatis的if标签对入参做一些判断，进行动态sql组装，现在的做法是必须使用DataQL， 在内部判断进行SQL组装，然后进行拼接，条件如果很多DataQL会非常复杂，难以维护，能否提供类似的机制，可以方便的新增SQL API实现动态SQL组装，比如：
`
select * from employee where 1=1 [and username = #{username}] [and dept_no = #{deptNo}]
`
这样如果参数传入username可以根据username查询， 如果传入deptNo可以根据deptNo查询，如果不传入则忽略[]里的查询条件

**Comment by zycgit** [comment]
https://www.hasor.net/web/dataql/fragment/sql/about_mybatis.html

新增了一个 @@mybatis 的能力，还原了几个 mybatis 。这个功能要感谢社区的贡献。
