### ISSUE TITLE
保存api之后，点击编辑再进入，没有显示之前保存的信息

### ISSUE THREAD

**Issue by fengsong89** [zycgit/hasor#29]
![image](https://user-images.githubusercontent.com/25579644/81248122-481e1000-904e-11ea-9d11-33b47a54abfe.png)

**Comment by zycgit** [comment]
4.1.4 版本 SQL 模式中已经确认存在这个问题，这个问题是前端页面中的 Bug。 已经在 即将发布的 4.1.5 中修复。

**Comment by meglory** [comment]
@zycgit 请问4.1.5版本什么时候发布？
