### ISSUE TITLE
新增api时，comment会覆盖掉第一行代码，导致看不到这行代码

### ISSUE THREAD

**Issue by fengsong89** [zycgit/hasor#30]
![image](https://user-images.githubusercontent.com/25579644/81248408-d85c5500-904e-11ea-8bc8-80bcdaab7bd9.png)

**Comment by zycgit** [comment]
第一行是一个注释， 这个 comment 在新增时候特意显示来。意图是让 使用者知道要为新 api 编写备注。 

可以点击 comment 右上角的那个 info 图标来关闭它

关于这个交互，欢迎探讨。

**Comment by fengsong89** [comment]
这个comment可以展示，修改的时候也可以展示，但是不要挡着第一行那个注释。这样用户用起来的时候会有疑惑。

**Comment by zycgit** [comment]
4.1.5 版本中，会把这个默认展示。变为默认不展示。
