### ISSUE TITLE
两个hite同时使用, 有一个不起作用

### ISSUE THREAD

**Issue by Haozi0456** [zycgit/hasor#31]
请问hint FRAGMENT_SQL_QUERY_BY_PAGE = true
hint FRAGMENT_SQL_COLUMN_CASE = "hump" 这两个同时使用, 为什么这个驼峰标识不起作用??

**Comment by zycgit** [comment]
4.1.4 版本和 4.1.3 版本中确认有这个问题，这个问题会在 4.1.5 中修复。
