### ISSUE TITLE
启用分页发布以后，GET请求数据的currentPage一直是0

### ISSUE THREAD

**Issue by Fym-NightGod** [zycgit/hasor#32]
在DataWay里面测试时，可以根据传入的page 参数正常分页查询和处理逻辑，但是发布以后，不管page是多少数字，都不会改变currentPage,currentPage会一直为0
![image](https://user-images.githubusercontent.com/39977972/81367954-2c376e80-9121-11ea-8551-4794f81d18a4.png)
![image](https://user-images.githubusercontent.com/39977972/81367983-42452f00-9121-11ea-871d-31506c564355.png)

**Comment by zycgit** [comment]
使用的是 GET 方法，get 方法参数获取采用的是 httpRequest.getParameterValues 拿到的就是 Sring 类型。

但是 Edit 页面中，参数的递交采用的是 POST， 请求参数中可以明确的表示是一个 number 类型。

这个办法建议将 4.1.5 中的 conver 函数库代码拷贝到你的工程中单独使用。

用法就是将 请求参数 用函数转换 成 int 类型。
