### ISSUE TITLE
减法问题，无法正常使用减号

### ISSUE THREAD

**Issue by Fym-NightGod** [zycgit/hasor#33]
## 报错
![image](https://user-images.githubusercontent.com/39977972/81368181-b5e73c00-9121-11ea-96d0-db8694048e56.png)
![image](https://user-images.githubusercontent.com/39977972/81368272-efb84280-9121-11ea-9219-e3d83ae76cd4.png)

## 正常
![image](https://user-images.githubusercontent.com/39977972/81368223-ceefed00-9121-11ea-896e-544f14754eea.png)

![image](https://user-images.githubusercontent.com/39977972/81368288-fcd53180-9121-11ea-912b-c2718687f7b3.png)

**Comment by zycgit** [comment]
和 https://github.com/zycgit/hasor/issues/32 是相同问题。
