### ISSUE TITLE
DataQL支持使用Headers参数

### ISSUE THREAD

**Issue by meglory** [zycgit/hasor#34]
RT. 目前有计划支持在DataQL中使用Headers参数嘛？@zycgit

**Comment by zycgit** [comment]
已经支持，只不过文档上没有写这个。 具体参考这个类：net.hasor.dataql.fx.web.WebUdfSource

在 4.1.5 时会把这个文档也放出来。

**Comment by meglory** [comment]
@zycgit 好的，多谢，请问4.1.5版本大概什么时间发布呢，另外，想问下，DataQL有没有相关的性能测试数据

**Comment by zycgit** [comment]
1.  4.1.5 正在准备发布，第一个会先放一个 beta 版本出来。
2.  性能这一块主要是2方面决定的
    1. 合理利用 Dataway 的 SPI 做一些缓存工作。比如：结果缓存、编译缓存
    2. SQL 查询场景下，优化 SQL 语句，不要返回过大的数据。


社区里面的情况不清楚，但是我们在一个大客户的场景下面压测下主要瓶颈在网络IO和后端数据库。

**Comment by meglory** [comment]
好的，非常感谢^_^
