### ISSUE TITLE
4.1.5和4.1.6都不可以保存接口，已确定4.1.4可以保存

### ISSUE THREAD

**Issue by tzxylao** [zycgit/hasor#37]
![UTOOLS1589098236725.png](https://user-gold-cdn.xitu.io/2020/5/10/171fda2cd9f7bd61?w=1448&h=780&f=png&s=65452)

**Comment by cubemoon** [comment]
重新再github上找下数据库sql，增加了新字段。

**Comment by zycgit** [comment]
《Dataway 4.1.5 以上版本升级指南》https://my.oschina.net/ta8210/blog/4275154
