### ISSUE TITLE
数据库utf8mb4格式的，注释保存乱码变??

### ISSUE THREAD

**Issue by tzxylao** [zycgit/hasor#38]
数据库utf8mb4格式的，注释保存乱码变??

**Comment by zycgit** [comment]
在 SaveApiController 类中断点，检查 参数 requestBody 中获取的参数是否已经乱码

- 如果拿到的参数已经乱码，请检查请求编码格式。设置成 utf-8
- 如果此时没有乱码，但是入库之后乱码，请检查数据库编码格式和数据库连接字符串。

**Comment by tzxylao** [comment]
解决了，数据库url上加 characterEncoding=UTF-8
