### ISSUE TITLE
4.1.6版本，保存测试发布接口后，调用提示 not found api

### ISSUE THREAD

**Issue by cubemoon** [zycgit/hasor#39]
{"success":false,"message":"404 : not found api.","code":404,"lifeCycleTime":69981,"executionTime":69977,"value":"not found api."}

**Comment by zycgit** [comment]
这个应该和版本无关系。

检查一下数据库中 interface_release 表中是否真的存在你的 API，Dataway 的发布操作会将你的 API 保存在这里。

**Comment by cubemoon** [comment]
刚查看了下，数据库中是有记录的

**Comment by zycgit** [comment]
还有一个情况，看一下你 API 发布的时候用的  httpmethod 和使用的时候 httpmethod 是不是不同了？

httpmethod  + api path 是唯一定位 api 的手段。

**Comment by cubemoon** [comment]
明白了，试了下果然是这个样子的。十分感谢回复。
