### ISSUE TITLE
如何把返回结果的默认结构去掉

### ISSUE THREAD

**Issue by tzxylao** [zycgit/hasor#40]
![image](https://user-images.githubusercontent.com/11553212/81496864-63f31180-92ed-11ea-8154-eeab104bc7a7.png)

**Comment by tzxylao** [comment]
apiBinder.bindSpiListener(ResultProcessChainSpi.class, new ResultProcessChainSpi() {
            @Override
            public Object callAfter(boolean formPre, ApiInfo apiInfo, Object result) {
                Map<String, Object> optionMap = apiInfo.getOptionMap();
                optionMap.put("resultStructure", false);
                apiInfo.setOptionMap(optionMap);
                return Result.ok(result);
            }
        });
这个这样可以解决

**Comment by zycgit** [comment]
界面配置。
![image](https://user-images.githubusercontent.com/4951471/81536913-ed165100-939e-11ea-9d53-db35f7f20210.png)
