### ISSUE TITLE
可以把JSON序列化这一步抽象出来吗

### ISSUE THREAD

**Issue by tzxylao** [zycgit/hasor#42]
https://github.com/zycgit/hasor/issues/41#issue-615660644

![image](https://user-images.githubusercontent.com/11553212/81543144-43d45880-93a8-11ea-9dc8-071419ae3580.png)

还是这个问题，我发现到我截图这步，已经把JSON.toJSONString的内容write到response了，好像没有别的办法进行中间拦截了，希望把JSON序列化这步分离出来，能让用户自定义实现

**Comment by zycgit** [comment]
如果是仅仅拦截结果的话可以用这个 ResultProcess拦截器 。
https://www.hasor.net/web/dataway/spi.html#resultprocess

**Comment by zycgit** [comment]
可以把JSON序列化这一步抽象出来吗？

**Comment by zycgit** [comment]
在 4.1.7 中会提供一个新的扩展接口 ResultSerializationChainSpi ，通过这个扩展接口可以实现自定义序列化。

**Comment by zycgit** [comment]
4.1.7 已发布，https://www.hasor.net/web/dataway/spi.html#serializationchainspi
