### ISSUE TITLE
查询interface_release 表是少个where关键字， 数据库是oracle

### ISSUE THREAD

**Issue by zhuhedong** [zycgit/hasor#45]
select * from (
            select * from interface_release pub_method = ? and pub_path = ? and pub_status = 0 order by pub_release_time desc
        ) t where rownum <= 1
     这是拼装后的sql

**Comment by zhuhedong** [comment]
hasor-dataway-4.1.5.jar!/net/hasor/dataway/daos/ReleaseDetail.ql  这个文件里面少了个where 关键字，麻烦修改下

**Comment by zycgit** [comment]
收到，目前最新是 4.1.6版本。4.1.7 中会加以修复

**Comment by zhuhedong** [comment]
有什么办法先临时解决一下吗

**Comment by zycgit** [comment]
下载 4.1.7 的代码自己本地手工编译大包一下。

**Comment by zycgit** [comment]
4.1.7 已发布
