### ISSUE TITLE
Dataway如何启用权限认证

### ISSUE THREAD

**Issue by oldbelvey** [zycgit/hasor#52]
Dataway如果支持了权限认证，感觉interface-ui页面基本可以在生产环境下使用了

**Comment by zycgit** [comment]
权限分为3个方面：
 - 1. interface-ui 页面的访问权限（4.1.8，可以借助 Pre 拦截器来和系统的权限整合到一起）
 - 2. interface-ui 页面的功能权限（4.1.9支持，目前还没有发布）
 - 3. API 的调用权限（4.1.9支持，目前还没发布）

**Comment by zycgit** [comment]
4.1.9 已经支持该功能。
SPI 为：net.hasor.dataway.spi.AuthorizationChainSpi

**Comment by zycgit** [comment]
see https://gitee.com/zycgit/hasor/issues/I1JA0Q
