### ISSUE TITLE
DataWay 关于整合Swagger的几个问题

### ISSUE THREAD

**Issue by nd49782** [zycgit/hasor#54]
在整合Swagger后，在DataWay中配置的接口中有Header参数，但是在Swagger UI中无法展现
![image](https://user-images.githubusercontent.com/45928087/85117816-06d66e00-b252-11ea-83fe-37b1fb8da559.png)
![image](https://user-images.githubusercontent.com/45928087/85117876-1bb30180-b252-11ea-84a9-5a7cd8ac5e1a.png)
因此无法填写header参数

还是上面的接口定义，在通过Swagger UI调试时，发现请求貌似发不出去的情况，导致无法调试
![image](https://user-images.githubusercontent.com/45928087/85118205-9a0fa380-b252-11ea-9b61-9cf7ef473746.png)
![image](https://user-images.githubusercontent.com/45928087/85118331-c4f9f780-b252-11ea-9f33-353706ee7819.png)
怀疑是BaseURL更改为主机名的原因，DataWay搭建在服务器中，我的本地环境并没有配置这个主机名映射（接口调用方人员更不会在本地去配置这个），所以想问一下有什么办法不让BaseURL更改为主机名吗？
![image](https://user-images.githubusercontent.com/45928087/85118706-43ef3000-b253-11ea-9789-0b865a19178e.png)

谢谢！

**Comment by zycgit** [comment]
see https://gitee.com/zycgit/hasor/issues/I1LC53

4.1.9 已经 release
