### ISSUE TITLE
f分页查询 null ExitType undefined  是什么错误

### ISSUE THREAD

**Issue by sunjunwei123** [zycgit/hasor#59]
{
  "success": false,
  "message": "null ExitType undefined.",
  "code": 500,
  "lifeCycleTime": 3,
  "executionTime": -1,
  "value": "null ExitType undefined."
}

mysql版本 5.7
dataway版本 4.1.7
![22fc218fad0bb0c6aaaf0a5fe93879c](https://user-images.githubusercontent.com/42828674/89540408-900c2900-d82f-11ea-8542-2755ce95700e.png)

**Comment by yaakua** [comment]
最后一句要加上return，我也被文档里面的代码坑了，跟踪了源码才发现的
示例:`hint FRAGMENT_SQL_QUERY_BY_PAGE = true
// 定义查询SQL
var dataSet = @@sql() <%
    select * from sys_user
%>
// 创建分页查询对象
var pageQuery =  dataSet();
// 设置分页信息
run pageQuery.setPageInfo({
    "pageSize"    : 10, // 页大小
    "currentPage" : 3   // 第3页
});
// 执行分页查询
return pageQuery.data();
`
