### ISSUE TITLE
可以在项目启动之后动态添加数据源

### ISSUE THREAD

**Issue by OopsFunyMudPee** [zycgit/hasor#61]
可以在项目启动之后动态添加数据源：
在项目启动之后，我可以随时添加，不同数据库，不同数据源，以满足我对很多数据库连接的需求

**Comment by LuxSun** [comment]
来  讨论讨论  我这边有三种解决方案~ QQ：28554482

**Comment by zycgit** [comment]
入 QQ 群也可以，193943114。官方的社区群

**Comment by zycgit** [comment]
4.1.x 升级到 4.1.13，或使用 4.2.x 版本

https://www.hasor.net/doc/display/dataql/LookupDataSourceListener
https://www.hasor.net/doc/display/dataql/LookupConnectionListener
