### ISSUE TITLE
版本4.2.0多条SQL执行报错

### ISSUE THREAD

**Issue by lijianmincn** [zycgit/hasor#66]
dataway版本4.2.0
数据：mysql  版本：5.7.30
数据库驱动 5.1.30

SQL：
hint FRAGMENT_SQL_MULTIPLE_QUERIES="last";
var dataSet = @@sql() <%
select * from sys_page_info;
SELECT LAST_INSERT_ID();
%>
return dataSet();

报如下错误：
{
  "success": false,
  "message": "[line 3:16~3:19 ,QIL 1:1] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT LAST_INSERT_ID()' at line 2",
  "code": 500,
  "lifeCycleTime": 73,
  "executionTime": -1,
  "value": "[line 3:16~3:19 ,QIL 1:1] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT LAST_INSERT_ID()' at line 2"
}

**Comment by zycgit** [comment]
![image](https://user-images.githubusercontent.com/4951471/95339025-28816100-08e6-11eb-95e1-071e852bb518.png)

**Comment by zycgit** [comment]
应该是 语言模式选择错误导致
