### ISSUE TITLE
参数校验手动抛出异常信息

### ISSUE THREAD

**Issue by isking2008** [zycgit/hasor#67]
目前在通过DataQL编写一些服务需要对参数做校验，或者业务规则判断， 如果校验失败手动抛出异常，并前台提示，之前Java也是类似处理方式，现在通过 `throw 500 "XX参数必填"`这种形式返回异常信息message中会有报错行信息，前台显示不友好

**Comment by zycgit** [comment]
![image](https://user-images.githubusercontent.com/4951471/96245887-724f0300-0fda-11eb-8da5-52cac85ab180.png)


没有复现。你看看代码中，是不是有这样的代码。像我这样把它注释掉。
`
//        apiBinder.bindSpiListener(ResultProcessChainSpi.class, new ResultProcessChainSpi() {
//            public Object callError(boolean formPre, ApiInfo apiInfo, Throwable e) {
//                return new HashMap<String, Object>() {{
//                    put("method", apiInfo.getMethod());
//                    put("path", apiInfo.getApiPath());
//                    put("errorMessage", e.getMessage());
//                }};
//            }
//        });
`
