### ISSUE TITLE
建议dataway界面的header配置参数直接放在http协议的请求头中

### ISSUE THREAD

**Issue by kiwimg** [zycgit/hasor#72]
建议dataway界面的header配置参数直接放在http协议的请求头中
1、这样符合协议要求，标准化，不是放在body中
2、可以在dataway界面模拟测试，类似postman，生产环境本来就界面
3、既可以通过dataQl函数或也可以自己通过标准java api获取

**Comment by zycgit** [comment]
4.2.2 中已加入。
