### ISSUE TITLE
响应数据乱码

### ISSUE THREAD

**Issue by fanchao892** [zycgit/hasor#73]
postman 测试接口 ，响应数据 汉字乱码

**Comment by zycgit** [comment]
你在应用里面设置一下编码格式，4.2.2 版本之后  内部已经不再主动设置任何编码格式了。

Module  里面用 WebApiBinder 下面两个方法

    /** 设置请求编码 */
    public WebApiBinder setRequestCharacter(String encoding);

    /** 设置响应编码 */
    public WebApiBinder setResponseCharacter(String encoding);
