### ISSUE TITLE
Bigint的数据类型返回有精度不准问题

### ISSUE THREAD

**Issue by liaostr** [zycgit/hasor#74]

**Comment by zycgit** [comment]
精度问题要设置几个 hint来达到你想要的目的

舍入模式：NUMBER_ROUNDING（默认：四舍五入）
对精度有较高要求需要设置：MIN_DECIMAL_WIDTH（默认为：double，改为 big）

https://www.hasor.net/doc/display/dataql/NUMBER_ROUNDING
https://www.hasor.net/doc/display/dataql/MIN_DECIMAL_WIDTH

**Comment by zycgit** [comment]
超过三个月的 issue 会被关闭，如果有类似问题和讨论可以开一个新的 issue。
