### ISSUE TITLE
接入nacos后rpc调用找不到接口的bug

### ISSUE THREAD

**Issue by lijiancn01** [zycgit/hasor#76]
nacos调用时id每次都重新生成，跟nacos配置的接口id匹配不上啊。
每次都报java.lang.NullPointerException: API is not published.
`@Override
    public String generateId(EntityDef objectType, String apiPath) {
        String generateId = null;
        if (this.enableHistory && EntityDef.RELEASE == objectType) {
            generateId = DatawayUtils.generateID();
        } else {
            try {
                MessageDigest mdTemp = MessageDigest.getInstance("SHA1");
                mdTemp.update(apiPath.getBytes());
                byte[] digest = mdTemp.digest();
                generateId = new BigInteger(digest).toString(24);
            } catch (NoSuchAlgorithmException e) {
                throw ExceptionUtils.toRuntimeException(e);
            }
        }
        return ((EntityDef.INFO == objectType) ? "i_" : "r_") + generateId.toLowerCase();
    }`

临时解决方案：配置HASOR_DATAQL_DATAWAY_NACOSDAL_HISTORY=false 可以暂时解决。

**Comment by zycgit** [comment]
已知的一个 Bug ， 4.2.2 中重写了 nacos 作为存储的那部分逻辑。之前的是在是有点复杂容易出错。

新的逻辑和老的逻辑目前是不兼容的，主要是体现在 保存在 nacos 中 api 索引信息的结构。 api 自身数据结构没有改变。
