### ISSUE TITLE
表名更换

### ISSUE THREAD

**Issue by Learnliang** [zycgit/hasor#81]
目前只能使用 interface_info、interface_release 这两张表表名，希望之后能够支持自定义表名

**Comment by zycgit** [comment]
收到

**Comment by zycgit** [comment]
master 上未发布的 4.2.2 中已经提供.

用法如下：

DataSource metadataDs = ...
apiBinder.bindType(InformationStorage.class).toInstance(() -> {
    return metadataDs;
});

**Comment by zycgit** [comment]
在 master 分支上，目标发布版本为 4.2.2 中提供支持。

通过配置 HASOR_DATAQL_DATAWAY_DB_TABLE_PREFIX 来指定两张表的表名前缀
