### ISSUE TITLE
能否支持多数据源？

### ISSUE THREAD

**Issue by mqinbin** [zycgit/hasor#83]
假设有 A、B、C三个数据库
其中A、B是需要对外提供的数据库
C中可以存放dataway所需的两张表。
这个需求如何配置？

**Comment by zycgit** [comment]
目前版本还不支持，主要是 C 目前还没有隔离机制。这个需求我研究研究加一下。

**Comment by zycgit** [comment]
目前 master 上已经可以支持 issue 中的诉求。目标发布版本为 4.2.2

用法如下：

DataSource metadataDs = ...
apiBinder.bindType(InformationStorage.class).toInstance(() -> {
    return metadataDs;
});

**Comment by zycgit** [comment]
// .DataSource form Spring boot into Hasor
        apiBinder.bindType(InformationStorage.class).toInstance(() -> {
            return this.metadataDs;
        });
        queryBinder.installModule(new JdbcModule(Level.Full, "ds1", this.dataDs1));
        queryBinder.installModule(new JdbcModule(Level.Full, "ds2", this.dataDs2));
