### ISSUE TITLE
返回值能否修改

### ISSUE THREAD

**Issue by liuzyong** [zycgit/hasor#85]
![image](https://user-images.githubusercontent.com/33834517/103609842-ba3a5200-4f59-11eb-8c95-6e14c31a1004.png)

如何把返回的json里面的value改成data。如上图

**Comment by 54corbin** [comment]
1:点击 'Structure' (JsonResult旁边)
![image](https://user-images.githubusercontent.com/21215811/108617904-bf455900-7454-11eb-84cb-4b5e71ad1081.png)

2:修改"value"为"data"
![image](https://user-images.githubusercontent.com/21215811/108617947-2e22b200-7455-11eb-892b-8de75eaa41e1.png)
