### ISSUE TITLE
Dataway 可以支持跨库查询吗？

### ISSUE THREAD

**Issue by luohengL** [zycgit/hasor#87]
现在项目中使用了dataway,面临需求需要跨库查询数据，请问目前可以支持吗？或者可以通过什么手段实现呢？

**Comment by bosiam** [comment]
前几天试用了下，目前好像只支持一个数据源（默认），相同数据源的不同库应该没问题吧

**Comment by luohengL** [comment]
> 前几天试用了下，目前好像只支持一个数据源（默认），相同数据源的不同库应该没问题吧

是的，在一次请求里，用hint指定数据源,是全局的，不能再次hint第二个数据源。但是如果是在同一数据库实例了，可以通过库名.表名访问其他库，不同实例就不行了。
我解决的办法是，使用import其他已经写好的DataQL查询，在主DataQL和引入的DataQL hint不同的数据源，可以实现分别查询，在组装数据。已成功在线上运行

**Comment by bosiam** [comment]
> > 前几天试用了下，目前好像只支持一个数据源（默认），相同数据源的不同库应该没问题吧
> 
> 是的，在一次请求里，用hint指定数据源,是全局的，不能再次hint第二个数据源。但是如果是在同一数据库实例了，可以通过库名.表名访问其他库，不同实例就不行了。
> 我解决的办法是，使用import其他已经写好的DataQL查询，在主DataQL和引入的DataQL hint不同的数据源，可以实现分别查询，在组装数据。已成功在线上运行

是在DataQL引用两个udf函数的方式？这样也不错，就是没有Sql模式那么灵活了

**Comment by zycgit** [comment]
在新的版本 4.2.2 里面 hint 可以在局部上生效。写法例如：

```
hint xxx = 1

...

{
   hint xxx =1
}

...


用一组花括号括起来，在花括号的前面可以声明 局部 hint 。这个文档上还没有更新。

```

**Comment by songjh513** [comment]
> > 我解决的办法是，使用import其他已经写好的DataQL查询，在主DataQL和引入的DataQL hint不同的数据源，可以实现分别查询，在组装数据。已成功在线上运行

您好，您这边引入其他已经写好的DataQL查询，这个import 的路径（资源路径)怎么写？需要把写好的查询 先拷贝出来放到项目的classpath中吗

![image](https://user-images.githubusercontent.com/17516346/132609709-285271ad-83a1-4ced-8d9f-06cade476eb1.png)

**Comment by luohengL** [comment]
> > > 我解决的办法是，使用import其他已经写好的DataQL查询，在主DataQL和引入的DataQL hint不同的数据源，可以实现分别查询，在组装数据。已成功在线上运行
> 
> 您好，您这边引入其他已经写好的DataQL查询，这个import 的路径（资源路径)怎么写？需要把写好的查询 先拷贝出来放到项目的classpath中吗
> 
> ![image](https://user-images.githubusercontent.com/17516346/132609709-285271ad-83a1-4ced-8d9f-06cade476eb1.png)

![image](https://user-images.githubusercontent.com/34935436/133186948-77233ca8-7832-494e-9dbf-005c6a2427fa.png)
直接import 配置的访问路径就行了，不用配classpath
