### ISSUE TITLE
dataql打算支持事务吗

### ISSUE THREAD

**Issue by cbz20000** [zycgit/hasor#89]
dataql打算支持事务吗？在官网上没看到怎么开启事务。
![image](https://user-images.githubusercontent.com/79636715/109156721-26903f80-77ac-11eb-85d7-364d50bb39fd.png)
![image](https://user-images.githubusercontent.com/79636715/109156740-2b54f380-77ac-11eb-9f9d-9e96a1affe36.png)
![image](https://user-images.githubusercontent.com/79636715/109156768-33ad2e80-77ac-11eb-9e9d-4d3ea9e2b763.png)

**Comment by zycgit** [comment]
有一个事务函数库。import 'net.hasor.dataql.fx.db.TransactionUdfSource' as tran;

但是没怎么测试，你可以先试一试。 有问题可以提出来。 net.hasor.dataql.fx.db.TransactionUdfSource 是它的类名，源码你可以进去看一下。
